task: binary
stage: adapt
seed: 2025
src_model: BackBone
src_dataset: FakeTT
tgt_dataset: FakeSV
adapt_method: RADAR
select_method: last_iterate
setting: online
para:
  num_retrieve: 6
  entropy_threshold: 0.51
  align_loss_weight: 1
  unfreeze_encoder: true
  aggregate_label: weighted_probs
  memory_size: 896
adapt:
  steps: 5
  batch_size: 128
datewise: batch-wise
tgt_data:
  fold: all
  split: all
  task: binary
opt:
  name: Adam
  lr: 0.001
  betas:
    - 0.9
    - 0.999
  weight_decay: 0
