task: binary
stage: adapt
seed: 2025
src_model: BackBone
src_dataset: FakeTT
tgt_dataset: FVC
adapt_method: RADAR
select_method: last_iterate
setting: online
para:
  num_retrieve: 6
  entropy_threshold: 0.24
  align_loss_weight: 5
  unfreeze_encoder: true
  aggregate_label: weighted_probs
adapt:
  steps: 3
  batch_size: 9
datewise: batch-wise
tgt_data:
  fold: event_sequence
  split: all
  task: binary
opt:
  name: Adam
  lr: 0.0001
  betas:
    - 0.9
    - 0.999
  weight_decay: 0
