data:
  task: binary
para: {}
opt:
  name: AdamW
  lr: 5e-4
  weight_decay: 5e-4
sche:
  name: DummyLR

num_epoch: 20
batch_size: 128
seed: 2025
model: Backbone
dataset: FakeTT
type: default
patience: 5
stage: pretrain
task: binary
